# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-21 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(upload_to='goods/images/'),
        ),
    ]
