# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20180321_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(storage='z0stmmmuxwji48sv6yloriuopqosi64y', upload_to='goods/images/'),
        ),
    ]
