# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20180322_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='goods/images/'),
        ),
    ]
