# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20180322_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinfo',
            name='ttitle',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
